# Generated by Django 4.0.5 on 2022-06-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0002_remove_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
